/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ['./src/**/*.{js,jsx,ts,tsx}', ['./app/**/*.{ts,tsx}']],
    theme: {
        extend: {
            fontFamily: {
                sans: '"Arial",--apple-system,BlinkMacSystemFont,"Segoe UI",Rot',
            },
            fontSize: {
                xs: ['1.2rem', '1'],
                sm: ['1.4rem', '1.25'],
                lg: ['1.8rem', '1.75'],
                xl: ['2rem', '1.75'],
                '2xl': ['2.4rem', '2'],
                '3xl': ['3rem', '2.25'],
                '4xl': ['3.6rem', '2.5'],
            },
            colors: {
                white: '#fff',
                primary: '#FCD535',
                'primary-focus': '#F0B90B',
                'primary-content': '#181720',
                secondary: '#FEF6D8',
                'secondary-focus': '#F8ECBC',
                'secondary-content': '#C99400',
                accent: '#F5F5F5',
                'accent-focus': '#EAECEF',
                'accent-content': '#707A8A',
                neutral: '#181A2A',
                'neutral-focus': '#131522',
                'neutral-content': '#EDF2F7',
                'base-100': '#FFFFFF',
                'base-200': '#FAFAFA',
                'base-300': '#B7BDC6',
                'base-400': '#474D57',
                'base-content': '#181A2A',
                'base-border': '#CFCFCF',
                info: '#01A9F2',
                'info-content': '#FFFFFF',
                success: '#0ECB81',
                'success-content': '#FFFFFF',
                warning: '#FBBD23',
                'warning-content': '#382800',
                error: '#F6465D',
                'error-content': '#FFFFFF',
            },
            spacing: {
                0: '0',
                1: '0.4rem',
                2: '0.8rem',
                3: '1.2rem',
                4: '1.6rem',
                5: '2rem',
                6: '2.4rem',
                7: '2.8rem',
                8: '3.2rem',
                9: '3.6rem',
                10: '4rem',
                11: '4.4rem',
                12: '4.8rem',
                'navigation-height': 'var(--navigation-height)',
            },
            fontWeight: {
                light: '400',
                normal: '500',
                bold: '600',
            },
            backgroundImage: {},
            boxShadow: {
                primary: '4px 4px 10px 5px rgba(0, 0, 0, 0.35)',
                secondary: '0px 4px 4px rgba(0, 0, 0, 0.25)',
            },
        },
    },
    plugins: [],
};
